// Generated by gencpp from file template_package_msgs/example.msg
// DO NOT EDIT!


#ifndef TEMPLATE_PACKAGE_MSGS_MESSAGE_EXAMPLE_H
#define TEMPLATE_PACKAGE_MSGS_MESSAGE_EXAMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace template_package_msgs
{
template <class ContainerAllocator>
struct example_
{
  typedef example_<ContainerAllocator> Type;

  example_()
    : first_name()
    , last_name()
    , age(0)
    , score(0)  {
    }
  example_(const ContainerAllocator& _alloc)
    : first_name(_alloc)
    , last_name(_alloc)
    , age(0)
    , score(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _first_name_type;
  _first_name_type first_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_name_type;
  _last_name_type last_name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint32_t _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::template_package_msgs::example_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::template_package_msgs::example_<ContainerAllocator> const> ConstPtr;

}; // struct example_

typedef ::template_package_msgs::example_<std::allocator<void> > example;

typedef boost::shared_ptr< ::template_package_msgs::example > examplePtr;
typedef boost::shared_ptr< ::template_package_msgs::example const> exampleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::template_package_msgs::example_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::template_package_msgs::example_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::template_package_msgs::example_<ContainerAllocator1> & lhs, const ::template_package_msgs::example_<ContainerAllocator2> & rhs)
{
  return lhs.first_name == rhs.first_name &&
    lhs.last_name == rhs.last_name &&
    lhs.age == rhs.age &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::template_package_msgs::example_<ContainerAllocator1> & lhs, const ::template_package_msgs::example_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace template_package_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::template_package_msgs::example_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::template_package_msgs::example_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::template_package_msgs::example_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::template_package_msgs::example_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_package_msgs::example_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::template_package_msgs::example_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::template_package_msgs::example_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8bfa80ae3c7a93455596d9622ad33a9";
  }

  static const char* value(const ::template_package_msgs::example_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8bfa80ae3c7a934ULL;
  static const uint64_t static_value2 = 0x55596d9622ad33a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::template_package_msgs::example_<ContainerAllocator> >
{
  static const char* value()
  {
    return "template_package_msgs/example";
  }

  static const char* value(const ::template_package_msgs::example_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::template_package_msgs::example_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first_name\n"
"string last_name\n"
"uint8 age\n"
"uint32 score\n"
;
  }

  static const char* value(const ::template_package_msgs::example_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::template_package_msgs::example_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_name);
      stream.next(m.last_name);
      stream.next(m.age);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct example_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::template_package_msgs::example_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::template_package_msgs::example_<ContainerAllocator>& v)
  {
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.first_name);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "score: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMPLATE_PACKAGE_MSGS_MESSAGE_EXAMPLE_H
